---
sudo: required
language: objective-c
osx_image: xcode7.3
install:

  # Install pip
  - sudo easy_install pip

  # Install homebrew
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # Install sublime
  - brew cask install sublime-text

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:

  # Ensure $PWD is the right folder.
  - cd $TRAVIS_BUILD_DIR

  # Check the role/playbook's syntax.
  - "ansible-playbook main.yml --syntax-check"

  # Test the playbook.
  - "ansible-playbook -i tests/inventory main.yml --connection=local --sudo"

  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - "ansible-playbook main.yml | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/